### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by zaur** [derosa/MultiImageChooser#1]
Seems like you removed too much)
not found resources:
R.layout.actionbar_custom_view_done_discard
R.id.actionbar_discard
R.id.actionbar_done

etc.

And better to mention that you are using ActionBarSherlock and android support library.

**Comment by derosa** [comment]
Uhm, looks like I pushed to the wrong remote repo... Those changes only have sense if used with my (private) app's theme. I'll revert back to the latest working status. Thanks for noticing and sorry!

**Comment by yiminlong** [comment]
Please fix this bug

**Comment by wyq01** [comment]
not found resources:
R.layout.actionbar_custom_view_done_discard
R.id.actionbar_discard
R.id.actionbar_done
R.style.CollageTheme

library:CollageTheme

**Comment by wyq01** [comment]
how to use your library

**Comment by derosa** [comment]
I branched the project so it doesn't use my private theme library, the theme-agnostic branch is https://github.com/derosa/MultiImageChooser/tree/notthemed

**Comment by wyq01** [comment]
thank u,but oom

At 2013-05-07 04:22:19,"David Erosa García" notifications@github.com wrote:

I branched the project so it doesn't use my private theme library, the theme-agnistic branch is https://github.com/derosa/MultiImageChooser/tree/notthemed

**Comment by derosa** [comment]
Please open a new issue for that oom with full stacktrace. It's working for me, try the standalone activity from the last commit.
